### ISSUE TITLE
help me!!!

### ISSUE THREAD

**Issue by huitc** [christophetd/CloudFlair#23]
```
$ python2 cloudflair.py --help
Traceback (most recent call last):
  File "cloudflair.py", line 4, in <module>
    import cloudflare_utils
  File "/data/data/com.termux/files/home/cloud2/cloudflare_utils.py", line 2, in <module>
    import ipaddress
ImportError: No module named ipaddress
```
```
$ python3 cloudflair.py --help
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "cloudflair.py", line 10, in <module>
    from html_similarity import similarity
ModuleNotFoundError: No module named 'html_similarity'
```

**Comment by huitc** [comment]
```
Command "/data/data/com.termux/files/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-t0wp5t1o/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-yya884w1/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-t0wp5t1o/lxml/
```

**Comment by christophetd** [comment]
Make sure you ran a `pip install -r requirements.txt` before running the tool.
