### ISSUE TITLE
Error while running normal test

### ISSUE THREAD

**Issue by taher-it** [christophetd/CloudFlair#24]
Traceback (most recent call last):
  File "cloudflair.py", line 167, in <module>
    main(args.domain, args.output_file, censys_api_id, censys_api_secret)
  File "cloudflair.py", line 136, in main
    hosts = find_hosts(domain, censys_api_id, censys_api_secret)
  File "cloudflair.py", line 21, in find_hosts
    if not dns_utils.is_valid_domain(domain):
  File "/root/Desktop/info gathering/CloudFlair/dns_utils.py", line 5, in is_valid_domain
    dns.resolver.query(domain, 'A')
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 1132, in query
    raise_on_no_answer, source_port)
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
  File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.0018880367 seconds

**Comment by christophetd** [comment]
What's your DNS server? Looks like a (temporary?) network issue to me

**Comment by christophetd** [comment]
Closing due to inactivity, feel free to reopen if needed.
