### ISSUE TITLE
python3 error

### ISSUE THREAD

**Issue by lijun199** [christophetd/CloudFlair#34]
Traceback (most recent call last):
  File "cloudflair.py", line 3, in <module>
    import dns_utils
  File "/root/Desktop/CloudFlair/dns_utils.py", line 1, in <module>
    import dns.resolver
ImportError: No module named 'dns'

**Comment by christophetd** [comment]
Did you run `pip install -r requirements.txt`?

**Comment by lijun199** [comment]
thanks your

Christophe Tafani-Dereeper <notifications@github.com>于2020年4月6日 周一下午8:25写道：
