### ISSUE TITLE
Help what is problem i,m use termux ??

### ISSUE THREAD

**Issue by ringawy** [christophetd/CloudFlair#35]
python2 cloudflair.py www.ikhwanonline.com
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "cloudflair.py", line 184, in <module>
    main(args.domain, args.output_file, censys_api_id, censys_api_secret)
  File "cloudflair.py", line 153, in main
    hosts = find_hosts(domain, censys_api_id, censys_api_secret)
  File "cloudflair.py", line 32, in find_hosts
    if not dns_utils.is_valid_domain(domain):
  File "/data/data/com.termux/files/home/CloudFlair/dns_utils.py", line 5, in is_valid_domain
    dns.resolver.query(domain, 'A')
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dns/resolver.py", line 1132, in query
    raise_on_no_answer, source_port)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.0032861233 seconds
$ python3 cloudflair.py www.ikhwanonline.com
cloudflair.py:46: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(cert_fingerprints) is 0:
cloudflair.py:55: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(hosts) is 0:
cloudflair.py:157: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(origins) is 0:
[*] Retrieving Cloudflare IP ranges from https://www.cloudflare.com/ips-v4
Traceback (most recent call last):
  File "cloudflair.py", line 7, in <module>
    import censys_search
  File "/data/data/com.termux/files/home/CloudFlair/censys_search.py", line 1, in <module>
    import censys.certificates
ModuleNotFoundError: No module named 'censys'

**Comment by christophetd** [comment]
Have you tried `pip install -r requirements.txt`?
