### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by NivinCNC** [christophetd/CloudFlair#60]
while executing i am getting this error
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/cloudflair/cloudflair.py", line 184, in <module>
    main(args.domain, args.output_file, censys_api_id, censys_api_secret)
  File "/data/data/com.termux/files/home/cloudflair/cloudflair.py", line 153, in main
    hosts = find_hosts(domain, censys_api_id, censys_api_secret)
  File "/data/data/com.termux/files/home/cloudflair/cloudflair.py", line 32, in find_hosts
    if not dns_utils.is_valid_domain(domain):
  File "/data/data/com.termux/files/home/cloudflair/dns_utils.py", line 5, in is_valid_domain
    dns.resolver.query(domain, 'A')
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/dns/resolver.py", line 1131, in query
    return get_default_resolver().query(qname, rdtype, rdclass, tcp, source,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/dns/resolver.py", line 1041, in query
    timeout = self._compute_timeout(start)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.002305269241333 seconds

**Comment by christophetd** [comment]
What domain are you running CloudFlair against?

**Comment by SpotnikSignal** [comment]
I had the same, for me it was removing https:// so like example.com
