### ISSUE TITLE
Facing this error

### ISSUE THREAD

**Issue by Lord-Ravan** [christophetd/CloudFlair#69]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7b587c9e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='search.censys.io', port=443): Max retries exceeded with url: /api/v2/hosts/68.232.201.126 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7b587c9e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/cloudflair/cloudflair.py", line 198, in <module>
    main(args.domain, args.output_file, censys_api_id, censys_api_secret, args.use_cloudfront)
  File "/root/cloudflair/cloudflair.py", line 167, in main
    hosts = find_hosts(domain, censys_api_id, censys_api_secret, use_cloudfront)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/cloudflair/cloudflair.py", line 68, in find_hosts
    hosts = censys_search.get_hosts(cert_fingerprints, censys_api_id, censys_api_secret)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/cloudflair/censys_search.py", line 46, in get_hosts
    hosts_search_results = censys_hosts.search(hosts_query).view_all()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/censys/search/v2/api.py", line 212, in view_all
    result = task.result()
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/censys/search/v2/api.py", line 262, in view
    return self._get(self.view_path + document_id, args)["result"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/censys/common/base.py", line 208, in _get
    return self._make_call(self._session.get, endpoint, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/censys/common/base.py", line 41, in _wrapper
    return _impl()
           ^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/censys/common/base.py", line 39, in _impl
    return method(self, *args, *kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/censys/common/base.py", line 165, in _make_call
    res = method(url, **request_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='search.censys.io', port=443): Max retries exceeded with url: /api/v2/hosts/68.232.201.126 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7b587c9e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by christophetd** [comment]
Looks like a network connection issue to censys. What do you get if you run this in your terminal?

```
dig +short search.censys.io
curl https://search.censys.io -v -o /dev/null
```

**Comment by Lord-Ravan** [comment]
┌──(kali㉿kali)-[~]
└─$ dig +short search.censys.io
;; communications error to 192.168.161.2#53: timed out
;; communications error to 192.168.161.2#53: timed out
;; communications error to 192.168.161.2#53: timed out
;; no servers could be reached

                                                                                                                                                                
┌──(kali㉿kali)-[~]
└─$ dig +short search.censys.io
104.26.10.245
104.26.11.245
172.67.68.81

**Comment by thehappydinoa** [comment]
I fixed a couple of the error handling issues in #70 but that looks like your router is having trouble with the search.censys.io dns resolution. Possibly restarting could help.
