### ISSUE TITLE
CensysCerts.search() missing 1 required positional argument: 'cursor'

### ISSUE THREAD

**Issue by darshanpjpt** [christophetd/CloudFlair#73]
I am facing the below error:

Traceback (most recent call last):
  File "/home/mylinux/tools/CloudFlair/cloudflair.py", line 213, in <module>
  File "/home/mylinux/tools/CloudFlair/cloudflair.py", line 182, in main
    hosts = find_hosts(domain, censys_api_id, censys_api_secret, use_cloudfront)
  File "/home/mylinux/tools/CloudFlair/cloudflair.py", line 64, in find_hosts
    cert_fingerprints = censys_search.get_certificates(domain, censys_api_id, censys_api_secret)
  File "/home/mylinux/tools/CloudFlair/censys_search.py", line 23, in get_certificates
    certificates_search_results = censys_certificates.search(
TypeError: CensysCerts.search() missing 1 required positional argument: 'cursor'

**Comment by darshanpjpt** [comment]
This error is showing in the latest commit, The commit b076c339656dc6310a93fc6a3f4492a0f5461642 works fine.

**Comment by christophetd** [comment]
Hello,

I just tested it and it seems to work fine. I updated the README with cleared install instructions - can you give it a try?

**Comment by darshanpjpt** [comment]
Yeah, it works perfectly.

Thanks a lot.
